# Copyright (c) Meta Platforms, Inc. and affiliates.

# pyre-unsafe
"""Routing testconfigs package — re-exports from member modules.

Allows callers to use the package-level path:
    from taac.testconfigs.routing import (
        CTE_UCMP_QZD_TEST,
    )

instead of the deeper module path.
"""

from taac.testconfigs.routing.cicd_ebb_int_tc import (
    BAG002_SNC1_CONVEYOR_TEST_CONFIG,
    BAG010_ASH6_BGP_STAGE1_CONVEYOR_TEST_CONFIG,
    BAG010_ASH6_BGP_STAGE1_CONVEYOR_TEST_UPDATE_GROUP_CONFIG,
    BAG010_ASH6_CONVEYOR_LONGEVITY_TEST_CONFIG,
    BAG010_ASH6_CONVEYOR_LONGEVITY_TEST_UPDATE_GROUP_CONFIG,
    BAG010_ASH6_DRAIN_CONVEYOR_TEST_CONFIG,
    BAG010_ASH6_DRAIN_CONVEYOR_TEST_UPDATE_GROUP_CONFIG,
    BAG010_ASH6_INSTABILITY_CONVEYOR_TEST_CONFIG,
    BAG010_ASH6_INSTABILITY_CONVEYOR_TEST_UPDATE_GROUP_CONFIG,
    BAG010_ASH6_RUNTIME_UPDATE_CONVEYOR_TEST_CONFIG,
    BAG010_ASH6_RUNTIME_UPDATE_CONVEYOR_TEST_UPDATE_GROUP_CONFIG,
    BAG011_ASH6_BGP_OSCILLATIONS_CONVEYOR_TEST_CONFIG,
    BAG011_ASH6_BGP_OSCILLATIONS_CONVEYOR_TEST_UPDATE_GROUP_CONFIG,
    BAG011_ASH6_BGP_RESTART_CONVEYOR_TEST_CONFIG,
    BAG011_ASH6_BGP_RESTART_CONVEYOR_TEST_UPDATE_GROUP_CONFIG,
    BAG011_ASH6_BGP_STABILITY_CONVEYOR_TEST_CONFIG,
    BAG011_ASH6_BGP_STABILITY_CONVEYOR_TEST_UPDATE_GROUP_CONFIG,
    BAG011_ASH6_BGP_STAGE1_CONVEYOR_TEST_CONFIG,
    BAG011_ASH6_BGP_STAGE1_CONVEYOR_TEST_UPDATE_GROUP_CONFIG,
)
from taac.testconfigs.routing.fboss_bgp_plus_plus_chronos_node_test_config import (
    build_bgp_dc_test_config,
)
from taac.testconfigs.routing.test_config_cte_ucmp import (
    CTE_UCMP_QZD_TEST,
)
from taac.testconfigs.routing.test_config_cte_ucmp_stand_alone import (
    CTE_UCMP_STAND_ALONE,
)

__all__ = [
    "BAG002_SNC1_CONVEYOR_TEST_CONFIG",
    "BAG010_ASH6_BGP_STAGE1_CONVEYOR_TEST_CONFIG",
    "BAG010_ASH6_BGP_STAGE1_CONVEYOR_TEST_UPDATE_GROUP_CONFIG",
    "BAG010_ASH6_CONVEYOR_LONGEVITY_TEST_CONFIG",
    "BAG010_ASH6_CONVEYOR_LONGEVITY_TEST_UPDATE_GROUP_CONFIG",
    "BAG010_ASH6_DRAIN_CONVEYOR_TEST_CONFIG",
    "BAG010_ASH6_DRAIN_CONVEYOR_TEST_UPDATE_GROUP_CONFIG",
    "BAG010_ASH6_INSTABILITY_CONVEYOR_TEST_CONFIG",
    "BAG010_ASH6_INSTABILITY_CONVEYOR_TEST_UPDATE_GROUP_CONFIG",
    "BAG010_ASH6_RUNTIME_UPDATE_CONVEYOR_TEST_CONFIG",
    "BAG010_ASH6_RUNTIME_UPDATE_CONVEYOR_TEST_UPDATE_GROUP_CONFIG",
    "BAG011_ASH6_BGP_OSCILLATIONS_CONVEYOR_TEST_CONFIG",
    "BAG011_ASH6_BGP_OSCILLATIONS_CONVEYOR_TEST_UPDATE_GROUP_CONFIG",
    "BAG011_ASH6_BGP_RESTART_CONVEYOR_TEST_CONFIG",
    "BAG011_ASH6_BGP_RESTART_CONVEYOR_TEST_UPDATE_GROUP_CONFIG",
    "BAG011_ASH6_BGP_STABILITY_CONVEYOR_TEST_CONFIG",
    "BAG011_ASH6_BGP_STABILITY_CONVEYOR_TEST_UPDATE_GROUP_CONFIG",
    "BAG011_ASH6_BGP_STAGE1_CONVEYOR_TEST_CONFIG",
    "BAG011_ASH6_BGP_STAGE1_CONVEYOR_TEST_UPDATE_GROUP_CONFIG",
    "CTE_UCMP_QZD_TEST",
    "CTE_UCMP_STAND_ALONE",
    "build_bgp_dc_test_config",
]
